import Head from 'next/head';

<Head>
<title>Books App</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head>
const BookEdit= () => {
     return (
          <div>
               <h1>BookEdit</h1>
          </div>
     );
};

export default BookEdit;