import Head from 'next/head';

<Head>
<title>Books App</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head>

export async function getStaticProps({ params }) {
     const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/books/${params.bid}`)

     const data = await res.json()

     return {
          props:{
               book: data
          }  
     }
}

export async function getStaticPaths() {
     const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/books`)

     const data = await res.json()

     return {
          Paths: data.map(book => ({
               params: { bid: String(book.id) }
          })),
          fallback: false
     }

}



const BookDetail= ({ Book }) => {
     return (
     <>
          <h1>{Book.title}</h1>
          <Link href="/libros">Book List</Link>
     </>
     );
};

export default BookDetail;